CONTRIBUTING.md, README.md, default.nix, shell.nix, src/Axiom/Set.agda, src/Axiom/Set/List.agda, src/Axiom/Set/Map.agda, src/Axiom/Set/Rel.agda, src/Axiom/Set/Sum.agda, src/Interface/Decidable/Instance.agda, src/Ledger.agda-lib, src/Ledger/PPUp.lagda, src/Ledger/PPUp/Properties.agda, src/Prelude.agda, stdlib-meta-update-imports.patch
Update ledger & the dependencies to Agda 2.6.3. This gives us a few nice things, in particular some improvements to metaprogramming and potentially quotients via erased cubical. It also means we don't have to rely on a custom patched version of Agda anymore.
=> Update to Agda 2.6.3

src/Ledger/Interface/HasCoin.agda, src/Ledger/PParams.lagda, src/Ledger/Prelude.agda, src/Ledger/Prelude/Base.agda, src/Ledger/TokenAlgebra.lagda, src/Ledger/Transaction.lagda
`Coin` was defined in multiple places before, leading to some issues with the Haskell build.
=> Move the definition of Coin into Ledger.Prelude.Base

default.nix
This is the source of the Haskell package, which can be useful for diagnosing issues with building it.
=> Add an executableSpecSrc attribute to the nix builds

.github/workflows/build.yml
to reduce the number of unnecessary rebuilds. 
Implementation notes:
The Github action build job is updated to :
- store in a cache:
* the result of nix-store --export  and
* a string formed of the names of the derivations that are being built
- import the cached store every time
- export the store only if the string containing the hashes changed
I added this extra thing with the hashes because exporting the store every time was taking a lot of time for the cases in which it didn't need to be re-exported.
The size of the exported cache is about 8GB but in the github UI it shows like 1.1GB, I guess because of the compression.
Because the cache can't be updated, I keep creating new ones when necessary (i.e. when the derivations changed). Apparently Github clears the old ones as you reach …
=> Cache nix store in github actions caches

src/Axiom/Set.agda, src/Axiom/Set/Map.agda, src/Axiom/Set/Map/Dec.agda, src/Ledger/Chain.lagda, src/Ledger/Deleg.lagda, src/Ledger/GovernanceActions.lagda, src/Ledger/Ledger.lagda, src/Ledger/Prelude.agda, src/Ledger/TokenAlgebra.lagda, src/Ledger/Transaction.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda
This PR adds certificates for delegation and DRep / staking pool (de)registration. The DELPL rule is renamed to CERT and a new VDEL rule was added to handle DRep certificates.
The deposits are being kept track of in the `deposits` map of `UTxOState`.
Also added a `unionWith` for monoids.
The computational and PoV proofs are incomplete and will have to be finished in a future PR.
=> Delegations and deposits

.github/workflows/build.yml, default.nix, src/formal-ledger.agda-lib
This improves consistency of package names, provides a single `Agda` package that should work for all purposes we had separate packages for previously and renames the generated PDFs. The produced files were called `PDF.pdf`, this renames them to `cardano-ledger.pdf` and `midnight-example.pdf` respectively.
=> Nix cleanup & improvements

src/Ledger/Deleg.lagda, src/Ledger/GovernanceActions.lagda, src/Ledger/Prelude.agda, src/Ledger/Ratify.lagda, src/Ledger/Transaction.lagda
This PR adds the `Voter` datatype. A voter can be either a credential voter that votes using a credential (such as DReps), an abstainer that always abstains, or a no confidence voter that always votes no to everything except the NoConfidence action. The autovoter votes are added as soon as a new action is proposed and these autovoters can be delegated to just like you would delegate to DReps.
resolves #91
=> Added autovoters

src/Axiom/Set.agda, src/Axiom/Set/Map.agda, src/Axiom/Set/Map/Dec.agda, src/Axiom/Set/Rel.agda, src/Ledger/Chain.lagda, src/Ledger/Deleg.lagda, src/Ledger/Ratify.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda
This PR adds DRep deposits to the stake distribution map. I also added `mapMaybeWithKeyᵐ` to make it easier to filter out credentials from the deposit map based on the `DepositPurpose`. The stakeDistrs are no longer passed to CHAIN as state, but rather calculated in the CHAIN rule from LState. Currently it only puts the DRep deposits into the map, the other stake distributions can be added in later PRs.
resolves #92
=> Make deposit contribute towards DRep votes

src/Ledger/Ledger.lagda, src/Ledger/Ledger/Properties.agda
A simple addition to `LEDGER`, but it was annoying to adjust the proofs properly. Closes #95.
=> Add governance incentives (reward gate)

src/Ledger/Deleg.lagda
The VDEL-deregdrep transition seemed to be adding the credential, not removing it.
=> Fixed a mistake in the VDEL rule

src/Ledger/Foreign/HSLedger.agda, src/Ledger/Introduction.lagda, src/Ledger/Transaction.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda
This PR adds the donations field to TxBody and updates the `pov` proof to account for that. I also extracted some lemmas from the pov proof and moved them to the `DepositHelpers` module.
resolves #109
=> Treasury donations

src/Ledger/Foreign/HSLedger.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/PParams.lagda, src/Ledger/Ratify.lagda
Closes #126. For now, we don't do anything special for withdrawals since it's not in the CIP anymore, but we can add some logic to make the threshold dependent on the withdrawal amount later.
=> Governance thresholds

src/Axiom/Set/TotalMap.agda, src/Axiom/Set/TotalMapOn.agda, src/Ledger/Prelude.agda
+  adds functionality to TotalMap module analogous to definitions in the Map module but using record types.
+  adds new module, `TotalMapOn`, with dependent record types for maps that are total on a given set `X : Set A`.
+  includes lookup and update functions as well as some lemmas about them.
=> Total map infrastructure

src/Axiom/Set.agda, src/Axiom/Set/TotalMap.agda, src/Ledger/PDF.lagda, src/Ledger/Prelude.agda, src/Ledger/TokenAlgebra/ValueSet.lagda
This PR provides a new module called Ledger.TokenAlgebra.ValueSet which uses the new functionality in TotalMap to define a token algebra using the Theory record of the Axiom.Set module.
To implement a token algebra using Set and modeling the value type as a total function on a given X : Set A I needed to add some functionality to TotalMap (and similar functionality to a new module, called TotalMapOn which restricts maps to the set X, but I have since abandoned the approach using TotalMapOn as I couldn't get it to work without adding a dependently typed version of the replacement axiom of the Set module, and we don't want to add axioms at this point for a number of reasons; this is why the comments below are crossed out).
The new functionality in TotalMap is part of a separate PR which …
=> TokenAlgebra Example: ValueSet

CONTRIBUTING.md, Makefile, README.md, shell.nix
This fixes `Makefile` being outdated & improves `shell.nix` to be able to use `Makefile` more conveniently.
=> Improve building the PDF via Makefile

default.nix, shell.nix
This fixes that the proper latex distribution was missing from the default nix shell. Before, `nix-shell --pure --command make` would fail because `latexmk` was missing, and this fixes it.
=> Fix missing latex dependency in `shell.nix`

Makefile
Change Makefile to use latexmk (so we don't have to compile multiple times to ensure all references are resolved) and move the resulting pdf to a file called cardano-ledger.pdf.
Somehow these improvements disappeared from @WhatisRT's earlier PR just before it was merged and I didn't notice until it was too late.
=> build-improvements-unclobber

default.nix
The change to the standard library is this:
https://github.com/input-output-hk/agda-stdlib/commit/bdfab77b179c937856c49d72321ca26e2a27d568
and makes the monoid solver not normalise goals before solving. This is what you want in most cases, and if you need normalisation the old version is still available as `solve-normalised`.
This fixes the performance issues type checking `Ledger.Utxo.Properties`.
=> Bump stdlib dependency to fix monoid solver performance

default.nix
The stdlib-meta commit is here:
https://github.com/input-output-hk/stdlib-meta/commit/897555aefd77c83e88492255641da3bcc4879461
This change brings type checking time of `Ledger.PParams` down from 45s to 2s.
=> Bump stdlib-meta dependency to fix for slow type checking of derived DecEq instances

.github/workflows/build.yml
Closes #167 
Adds a job at the beginning of the workflow which removes unnecessary software, thus allowing more space for the build. 
Below is the screenshot of running `df -a` at the end of the workflow, showing that the risk of running out of disk space is (currently) alleviated
=> Maximize build space

.github/workflows/build.yml
To avoid the mirrors not being found when uninstalling things, we need to run `apt-get update` at the beginning. 
When uninstalling to free space, removing "large packages" seems to take the longest, but only frees about 4GBs, so I removed this action in order to save  some build time.
=> Adjust maximize buildspace

src/Ledger/Deleg.lagda, src/Ledger/Utxow.lagda
Closes #148. ATM all certs require a credential, which is not true in Shelley, but that's a problem to solve in the future.
=> Add witness checks for certificates

src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda
This cleans up imports of one module---`Utxo.Properties`
It is based on [william/34-type-classes](https://github.com/input-output-hk/formal-ledger-specifications/tree/william/34-type-classes), so the diffs will be large at first, but will become small---limited to just the imports and private variable definitions of the `Utxo.Properties` module---once `william/34-type-classes` is merged.
=> Cleanup imports in module `Utxo.Properties`

src/Interface/HasSubtract.agda, src/Interface/HasSubtract/Instance.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/Prelude.agda, src/Ledger/Utxo/Properties.lagda, src/Tactic/DeriveComp.agda
This addresses issue #34 for the special case of subtraction in the `GovernanceActions`, `Utxo.Properties`, and `Tactic/DeriveComp` modules.
The goal of this PR is to allow us to use a single operation symbol, _-_, to denote subtraction over each of the types ℤ, ℕ, and Coin (which is currently just an alias for ℕ).
=> Type classes for common structures: subtraction

src/Ledger/Chain.lagda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/Ledger.lagda, src/Ledger/Ratify.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxow.lagda, src/Ledger/Utxow/Properties.agda
Closes #143. It's a bit annoying that we need to put something new in `UTxOEnv`, but there's no way around that.
=> Add proposal policy

src/Ledger/Chain.lagda, src/Ledger/Epoch.agda, src/Ledger/Gov.lagda, src/Ledger/GovernanceActions.lagda, src/Ledger/PParams.lagda, src/Ledger/Ratify.lagda
They are removed at the same epoch where they come into effect (via rollover of `EnactState`). Fixes #180.
=> Fix that governance actions were removed immediately

src/Interface/ComputationalRelation.agda, src/Interface/STS.agda, src/Ledger/Chain.lagda, src/Ledger/Chain/Properties.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/PDF.lagda, src/Ledger/Ratify.lagda, src/Ledger/Ratify/Properties.agda
This is important since we can get stuck on an epoch boundary otherwise. This also moves the treasury from `EnactState` into `EnactEnv`, which is equivalent but cleaner.
Closes #194.
=> Make `RATIFY` total

src/Ledger/GovernanceActions.lagda
`ENACT` was changed & we also got a `Computational` instance, but the two were incompatible.
=> Fix: Rebase broke master

src/Foreign/Convertible.agda, src/Interface/Decidable/Instance.agda, src/Ledger/Chain.lagda, src/Ledger/Gov.lagda, src/Ledger/PParams.lagda, src/Ledger/Prelude.agda, src/Ledger/Utxow.lagda
This doesn't do anything about #212, the existing definition of the rule *is* computational even without enforcing unique GovActionIds.
Question: This defines `any⇔∃` locally with the computational instance, but it feels like something that should either already be in the standard library (where I couldn't find it), or be defined in some more reasonable place in our repo.
=> Computational instance for GOV' rule

src/Interface/Bifunctor.agda, src/Interface/ComputationalRelation.agda, src/Interface/Functor.agda, src/Interface/STS.agda, src/Ledger/Chain.lagda, src/Ledger/Chain/Properties.agda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/Gov.lagda, src/Ledger/GovernanceActions.lagda, src/Ledger/Ledger.lagda, src/Ledger/Ledger/Properties.agda, src/Ledger/Prelude.agda, src/Ledger/Ratify.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda, src/Ledger/Utxow.lagda, src/Ledger/Utxow/Properties.agda, src/MidnightExample/HSLedger.agda, src/Prelude.agda
Provides a uniform way (i.e. typeclass) to perform (bi)functorial actions, rather than having to remember the names of each instantiation/module.
=> Introduce (Bi)functor interface

src/Interface/ComputationalRelation.agda, src/Interface/STS.agda, src/Ledger/Deleg.lagda, src/Ledger/Gov.lagda, src/Ledger/GovernanceActions.lagda, src/Ledger/Ledger.lagda, src/Ledger/Ledger/Properties.agda, src/Ledger/PPUp/Properties.agda, src/Ledger/Prelude.agda, src/Ledger/Ratify.lagda, src/Ledger/Ratify/Properties.agda, src/Ledger/Utxo.lagda, src/Ledger/Utxow/Properties.agda, src/MidnightExample/Ledger.lagda, src/Tactic/DeriveComp.agda
Also
- make SS⇒BS more amenable to instance search
- cleaned up Computational instance for LEDGER
Fixes #211
=> Remove the old Computational in favour of the new representation

.github/workflows/build.yml
Fix #230 (introduced by PR #217).
=> CI: fix deployment of PDFs

src/Axiom/Set/List.agda, src/Foreign/Convertible.agda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/Prelude.agda, src/Ledger/Utxo.lagda, src/MidnightExample/HSLedger.agda
- In light of a recent issue with `--overlapping-instances`
(c.f. https://github.com/agda/agda/issues/6895), I removed
all uses of overlapping in the codebase, which we actually redundant.
- `Foreign.Convertible` no longer overlaps instances of `Coercible`.
- `Axiom.Set.List` now exports general decidable equality to avoid ambiguity
when `Interface.DecEq.DecEq⇒Dec` is also in scope.
=> Remove --overlapping-instances

src/Axiom/Set/Map.agda, src/Ledger/Chain.lagda, src/Ledger/Ratify.lagda, src/Ledger/Utxo.lagda, src/Tactic/ByEq.agda
- Introduce the `by-eq` tactic that automates proofs of the form:
`λ where _ refl _ refl → refl`
- Use on injectivity proofs for `Axiom.Set.Map:mapKeys`, replacing the explicit argument of an injectivity proof with a tactic argument that invokes `by-eq`.
=> Tactic to remove trivial injectivity proofs

src/Axiom/Set/Map.agda, src/Interface/Decidable/Instance.agda, src/Interface/IsSet.agda, src/Ledger/Chain.lagda, src/Ledger/Chain/Properties.agda, src/Ledger/Deleg.lagda, src/Ledger/Epoch.agda, src/Ledger/Gov.lagda, src/Ledger/GovernanceActions.lagda, src/Ledger/Ledger.lagda, src/Ledger/Ledger/Properties.agda, src/Ledger/NewPP.lagda, src/Ledger/PDF.lagda, src/Ledger/PPUp.lagda, src/Ledger/PPUp/Properties.agda, src/Ledger/PParams.lagda, src/Ledger/Prelude.agda, src/Ledger/Ratify.lagda, src/Ledger/TokenAlgebra/ValueSet.lagda, src/Ledger/Transaction.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda, src/Ledger/Utxow.lagda, src/Ledger/Utxow/Properties.agda
Cleanup I did for the talk at the R&D seminar
=> PDF cleanup

.github/workflows/build.yml
to prevent fake successful builds: the build succeeding after the nix-command failed.
The processing of the nix-build command is causing the exit code of the nix command to be ignored. 
In this PR we are processing the result in a new step, so that if "nix-build" or "nix-store" fails, the build is also failing. 
For example, this is a PR reverting to a commit that caused a Haskell compilation error (and hence a nix-build failure) when building ledger: https://github.com/teodanciu/formal-ledger-specifications/pull/2
This build was "fake" succeeding. 
With the change in this commit, it is failing: https://github.com/teodanciu/formal-ledger-specifications/actions/runs/6456348932/job/17525659662?pr=2#step:10:5606
=> Respect the exit status of `nix` commands

src/Ledger/GovernanceActions.lagda
Fix documentation of types in Fig 6.
Addresses an item in issue #146.
=> PDF cleanup: Fig 6 documentation

src/Everything.agda, src/Interface/ComputationalRelation.agda, src/Interface/Decidable/Instance.agda, src/Ledger/Chain.lagda, src/Ledger/Chain/Properties.agda, src/Ledger/Introduction.lagda, src/Ledger/Ledger/Properties.agda, src/Ledger/NewPP.lagda, src/Ledger/NewPP/Properties.agda, src/Ledger/Ratify.lagda, src/Ledger/Ratify/Properties.agda, src/Ledger/Utxo/Properties.lagda
Fixes #147
This adds Computational instances for the remaining rules.
Also fixes some minor issues in a few of the rules (`RATIFY'`, `NEWPP` and `CHAIN`)
=> Final computational instances

src/Ledger/Address.lagda, src/Ledger/GovernanceActions.lagda
Fix spacing/alignment in Figures 4 and 6 as suggested in two items of issue #146.
=> PDF cleanup: fix spacing in Figures 4 and 6

src/Axiom/Set/Map.agda, src/Ledger/Ratify.lagda
Remove `sp-∘` from that figure, introduce a notation for division where division by zero gets mapped to zero and remove some unused pieces.
=> PDF cleanup: Fig 36 (improved)

src/Ledger/Abstract.agda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/Foreign/LedgerTypes.agda, src/Ledger/Ratify.lagda, src/Ledger/ScriptValidation.agda, src/Ledger/Transaction.lagda, src/Ledger/Utxow.lagda
Closes #125. I've also switched `scriptsNeeded` to the `credsNeeded` based version, which removes a bit of code duplication, and should hopefully be cleaner.
=> Add Vote and Propose script purposes

src/Ledger/Ratify.lagda, src/latex/agda-latex-macros.sty
Rearrange code to simplify nested where blocks in Fig 34, as suggested in one of the items in issue #146.
=> PDF cleanup: simplify code in Figure 34

.github/workflows/build.yml, README.md
- HTML links changed after #255, which this hotfix remedies.
- Also include links to generated Haskell.
=> README: fix links to HTML + add links to Haskell tests

src/Ledger/hs-src/cardano-ledger-executable-spec.cabal, src/Makefile
This PR renames the package of the Haskell executable spec to `cardano-ledger-executable-spec` to avoid name collision with the other `cardano-ledger` package.
=> Renamed the cabal project of the executable spec

.github/workflows/build.yml, default.nix, nix/sources.json, nix/sources.nix, src/Ledger/Epoch.agda, src/Ledger/Gov.lagda, src/Ledger/PPUp/Properties.agda, src/Ledger/Utxo.lagda
These are the minimal changes required to build with Agda 2.6.4.
I am clueless when it comes to nix, so I need some help:
- I updated the commit hashes for stdlib and stdlib-meta in `default.nix` but it didn't complain about the sha256 hash being the same as before.
- I don't know how to get Agda 2.6.4 in the nix shell
=> Agda 2.6.4 migration

src/Ledger/Foreign/HSLedger.agda, src/Ledger/PParams.lagda
Closes #271. We should probably clean this thing up and expose it in the PDF soon (#273)
=> Require `ppdWellFormed` to imply non-empty `updateGroups`

src/Ledger/Deleg.lagda, src/Ledger/Ledger.lagda, src/Ledger/Ledger/Properties.agda
- Check that pools that we delegate to exist. This is part of Shelley, but somewhat hidden (in the `DELEGS` inductive rule, which is analogous to `CERT` in Conway). This adds it to `DELEG`, where it belongs.
- Implement (Shelley-era) withdrawal logic and the [reward gate](https://github.com/cardano-foundation/CIPs/tree/master/CIP-1694#incentives-for-ada-holders-to-delegate-voting-stake), which was still missing. Withdrawals aren't included in `consumed` and and rewards pot isn't included in `HasCoin` of `LState`, so they don't actually add money back into the UTxO set (and it doesn't break POV).
=> Conway cert features

default.nix
Addresses parts of #279. I can't test this on my main machine since nix on macos sets the locale automagically. @omelkonian, do you want to rebase your PR on top of this to see if it works, and if it does you can merge this PR?
=> Add correct locales to everything

src/Ledger/Gov.lagda
This addresses one issue of #288.
Move let bindings above horizontal lines to improve readability of deduction rule.
=> Various cleanup items: Fig 15 -- format

src/Ledger/Chain.lagda, src/Ledger/PParams.lagda
This addresses an item of issue #288.
After it is defined, `Acnt` doesn't show up again until the "Blockchain Layer" section (currently Sec 15 on page 45), by which point readers will have long forgotten how it was defined.  This PR hides the definition of the `Acnt` record and then explains what it's for in prose near where it first appears in the pdf (in the "Blockchain Layer" section).
=> Various cleanup items: Fig 13 -- hide Acnt

src/Ledger/Utxo.lagda
This addresses one item of issue #289
We simply split off the latter part of the figure into its own figure which appears on the succeeding page.
=> Other pdf cleanup items: Fig 21 too big

.github/workflows/build.yml
Since we are importing IOG's nix cache, there is no longer need for that much storage to warranty a call to action `free-disk-size` which delays a CI run by a couple of minutes.
=> CI: remove `free-disk-space`

.github/workflows/build.yml, .gitignore, default.nix, src/checkTypeChecked.sh, src/typeCheck.sh
This PR introduces a `typeCheck.sh` script that measure the total time of typechecking `Everything.agda` and then records individual module times under `typecheck.time` (by looking at the modification dates of `.agdai` files).
That way, we can check that our changes do not terribly slow down typechecking by looking at the generated file in the `gh-pages` branch (or the CI artifact attached to the current PR).
Moreover, we can run the script through our whole (git) history to discover previously introduced regressions, but that can be done independently offline.
@WhatisRT has mentioned that the [ledger team](https://github.com/input-output-hk/cardano-ledger) actually creates nice graphs from such time durations, which we should definitely investigate to track typechecking performance …
=> CI: record typechecking times

.github/workflows/build.yml
Since we can just fetch our stuff from hydra now, we don't need to maintain a cache ourselves anymore. This should also speed up the action a bunch.
This removes freeing up space, fetching the cache and adding to the cache, which took around 5:30 min. This also reveals that our current HTML derivations aren't cached by Hydra, which eats up 2:30 min of that gained time, but only on PRs that don't change any Agda code. So this should almost always save us the full 5ish minutes.
=> Remove custom caching

src/Ledger/Address.lagda, src/Ledger/Chain.lagda, src/Ledger/Gov.lagda, src/Ledger/Utxo.lagda, src/latex/agda-latex-macros.sty
Addresses the following items of issue #282:
=> Explain symbols

src/Foreign/Convertible.agda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/Foreign/LedgerTypes.agda, src/Ledger/hs-src/test/UtxowSpec.hs
Adds `TxCert` and some additional required types to `LedgerTypes`
=> Added TxCerts to LedgerTypes

src/Data/List/Relation/Binary/Sublist/Ext.agda, src/Data/List/Relation/Unary/MOf.agda, src/Interface/ToBool.agda, src/Ledger/Address.lagda, src/Ledger/Gov.lagda, src/Ledger/PPUp.lagda, src/Ledger/PPUp/Properties.agda, src/Ledger/Prelude.agda, src/Ledger/Ratify.lagda, src/Ledger/Script.lagda, src/Ledger/ScriptValidation.agda, src/Ledger/Set/Theory.agda, src/Ledger/Transaction.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxow.lagda, src/Prelude.agda, src/Reflection/Ext.agda, src/Tactic/DeriveComp.agda, src/latex/agda-latex-macros.sty
*Depends on #301*
---
- Introduces generalised branching on boolean-like things such as
Bool/Maybe/Dec in `Interface.ToBool` and replaces all branching
variations with this approach uniformly.
- [Gov] More standard predicates isCC/isDRep/isSPO as inductive datatypes
- [Set/Map] hide decision procedures from the user-facing API
- [Script] Significant refactoring of `Ledger.Script.evalTimelock`:
+ Heal boolean blindness by replacing function (... -> Bool) with the
proper decision procedure for `evalTimelock`
+ Extra lemma for List.Sublist in `Data.List.Relation.Binary.Sublist.Ext`
+ Factored out m-of-n predicate (+ its dec.proc.) in `Data.List.Relation.Unary.MOf`
- [Prelude] introduce polymorphic unit as ⊤↑/tt↑
=> [fix #36, #281] consistent use of decision procedures

src/Ledger/Utxo/Properties.lagda, src/Tactic/MonoidSolver/NonNormalising.agda
This gives a significant speedup to the proofs in  `Ledger.Utxo.Properties` (from 30s total to 10s total).
=> Add a version of the monoid solver that tries first without normalising

src/Interface/HasOrder.agda, src/Interface/HasOrder/Instance.agda, src/Prelude.agda
This popped up while I reviewed #309, which adds a module qualifier to `_≥_`. This won't be necessary after this PR.
=> Add `_≥_` and `_>_` to `HasPreorder` and `ℚ` instance

src/Data/List/Ext.agda, src/Data/List/Relation/Unary/MOf.agda, src/Ledger/Script.lagda, src/Reflection/Ext.agda, src/Tactic/Inline.agda
~- `Script.evalTimelock`: works for all? and any?, but not MOf~
now fixed by an improved version of `MOf?` by Ulf (posted on Slack)
=> Tactic: inlining prototype

src/Axiom/Set/Sum.agda, src/Interface/IsCommutativeMonoid.agda, src/Ledger/Chain.lagda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/GovernanceActions/Properties.agda, src/Ledger/Prelude.agda, src/Ledger/Ratify.lagda, src/Ledger/Script.lagda, src/Ledger/Set/Theory.agda, src/Ledger/TokenAlgebra.lagda, src/Ledger/TokenAlgebra/ValueSet.lagda, src/Ledger/Utxo.lagda
This sits between `CommutativeMonoid` and `IsCommutativeMonoid`. It doesn't bundle the carrier but everything else. It is a lot better behaved as a typeclass than the other two, and enables a bunch of cleanup.
=> Add `IsCommutativeMonoid'` typeclass

src/Ledger/Chain.lagda, src/Ledger/Chain/Properties.agda, src/Ledger/Deleg.lagda, src/Ledger/Deleg/Properties.agda, src/Ledger/Epoch.lagda, src/Ledger/Epoch/Properties.agda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/Gov.lagda, src/Ledger/Gov/Properties.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/GovernanceActions/Properties.agda, src/Ledger/PDF.lagda, src/Ledger/PParams.lagda, src/Ledger/Script.lagda, src/Ledger/Transaction.lagda, src/Ledger/Types/Epoch.agda, src/Ledger/Types/GovStructure.agda
This matches how it's done in the Shelley spec, and makes things a little simpler. I also went and simplified `EPOCH` as much as I could. Closes #287.
=> Split `NEWEPOCH` into `EPOCH` and `NEWEPOCH`

src/Interface/ComputationalRelation.agda, src/Ledger/Chain/Properties.agda, src/Ledger/Deleg/Properties.agda, src/Ledger/Epoch/Properties.agda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/Foreign/LedgerTypes.agda, src/Ledger/Gov/Properties.agda, src/Ledger/GovernanceActions/Properties.agda, src/Ledger/Ledger/Properties.agda, src/Ledger/NewPP/Properties.agda, src/Ledger/PPUp/Properties.agda, src/Ledger/Prelude.agda, src/Ledger/Ratify/Properties.agda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda, src/Ledger/Utxow/Properties.agda, src/Ledger/hs-src/cardano-ledger-executable-spec.cabal, src/Ledger/hs-src/test/UtxowSpec.hs, src/MidnightExample/HSLedger.agda, src/MidnightExample/Ledger.lagda, src/MidnightExample/hs-src/midnight-example.cabal
This PR changes the output type of `computeProof` to `ComputationResult` which can return an error value if the computation fails.
=> Computational errors

README.md
This repository is now owned by Intersect, so we need to adjust a bunch of links.
=> Update README to reflect repository move

src/Interface/HasAdd.agda, src/Interface/HasSubtract.agda, src/Ledger/Abstract.agda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/PParams.lagda, src/Ledger/Prelude.agda, src/Ledger/Set/Theory.agda, src/Ledger/TokenAlgebra.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda, src/Ledger/hs-src/test/UtxowSpec.hs
This is a small addition to the fee calculation in Conway. Since we don't have Babbage features the `refScripts` function is just the constant empty set ATM. Also, since we don't have a way to compute a size for scripts in general, `scriptSize` is just an abstract function.
One annoyance is that we don't have types & functions to deal with rational numbers in the unit interval. So the new parameter doesn't have that constraint for now, but we should probably add that later.
Closes #345
=> Add `minFeeRefScriptsCoinsPerByte`

src/Ledger/Foreign/HSLedger.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/PParams.lagda, src/latex/agda-latex-macros.sty
This adds another threshold and the `SecurityGroup`. Closes #351
=> Add security-relevant parameters

src/Interface/HasSubtract.agda, src/Interface/HasSubtract/Instance.agda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda, src/Prelude.agda
This addresses one item of issue #282 by generalizing the `HasSubtract` typeclass and ...and removing unnecessary use of tactics in a few places.
=> PDF cleanup 282: rename `_⊖_` to `_-_`

src/Ledger/Script.lagda, src/Ledger/TokenAlgebra/ValueSet.lagda
This addresses one item of issue #282.
=> PDF cleanup 282: hide `module` syntax

src/Ledger/NewPP.lagda, src/Ledger/Ratify.lagda, src/Ledger/TokenAlgebra.lagda, src/Ledger/Utxow.lagda
This addresses one item of issue #282.
=> PDF cleanup: hide `λ where` syntax

src/Ledger/Address.lagda, src/Ledger/Introduction.lagda
This addresses one item of issue #282.
One way to hide `Σ` is to simply use an alternative `Σ-syntax` definition.  
This PR does this in the two places where `Σ` had appeared in a pdf figure (`Ledger.Introduction` and `Ledger.Address`).
=> PDF cleanup 282: hide `Σ`

default.nix, src/Everything.agda, src/Foreign/Convertible.agda, src/Foreign/Convertible/Deriving.agda, src/Foreign/Convertible/DerivingTest.agda, src/Ledger/Foreign/HSLedger.agda, src/Tactic/Inline.agda
I had to make a small fix to agda-stdlib-meta to work around agda/agda#7187. I put it on our fork here: input-output-hk/stdlib-meta@4fc4b1ed on top of the `v2.0-rc1` tag.
=> Deriving tactic for Convertible instances

src/Ledger/Ledger.lagda, src/Ledger/Ledger/Properties.agda
This is in the Alonzo spec but was apparently missing
=> Split LEDGER into valid and not valid cases

src/Ledger/Utxo.lagda, src/Ledger/hs-src/test/UtxowSpec.hs
Closes #354. This will also allow reference inputs in conformance tests.
=> Require reference inputs to be disjoint from regular inputs

src/Ledger/Ratify.lagda
Only resigned CC members were excluded, this is now fixed.
=> Fix CC expiration not being considered for `ccMinSize` check

src/Ledger/Gov.lagda, src/Ledger/Gov/Properties.agda
This reduces runtime from O(n!) to O(n). We should then prove that `allEnactable` is an invariant of `GOV`.
=> Replace `allEnactable` with `hasParent` in `GOV`

src/Ledger/Gov.lagda, src/Ledger/Gov/Properties.agda
`hasParent` was passed the current transaction ID instead of previous transaction ID in the `GOV` rule.
=> Fix `hasParent`

src/Interface/ComputationalRelation.agda, src/Interface/STS.agda, src/Ledger/Ledger/Properties.agda
The step for the head of a list is now done with argument `0`.
=> Reverse the index of `ReflexiveTransitiveClosureᵢ`

src/Ledger/Foreign/HSLedger.agda, src/Ledger/Foreign/LedgerTypes.agda, src/Ledger/Set/Theory.agda, src/Ledger/hs-src/cardano-ledger-executable-spec.cabal, src/Ledger/hs-src/test/UtxowSpec.hs, src/MidnightExample/hs-src/midnight-example.cabal
This PR introduces some changes that I deemed useful for conformance testing the `GOV` rule.
* Added a newtype wrapper around `TxId` to make it easier to pretty print the hash during conformance testing.
* Changed the representation of `CostModel` to `⊤`.
* Modeled `PParamUpdate` as `ℕ` to make it possible to update just the `minfeeA` parameter. This should be extended at some point to include all of the parameters.
=> GOV Conformance

src/Interface/ComputationalRelation.agda, src/Ledger/Chain/Properties.agda, src/Ledger/Deleg.lagda, src/Ledger/Deleg/Properties.agda, src/Ledger/Foreign/HSLedger.agda, src/Ledger/Foreign/LedgerTypes.agda, src/Ledger/Gov/Properties.agda, src/Ledger/Ledger/Properties.agda, src/Ledger/PParams.lagda, src/Ledger/Ratify/Properties.agda, src/Ledger/hs-src/test/UtxowSpec.hs, src/ScriptVerification/Lib.agda
Makes some changes for conformance testing the `CERT` rule:
* Added necessary `LedgerTypes` and `Convertible` instances
* Added a newtype wrapper for `HSMap` to make it easier to work with maps in conformance testing
* ~~Removed `CommutativeMonoid` requirement from `_∪⁺_` and `aggregate₊` (I ended up not actually needing this, but I think it still makes sense)~~
* Replaced some hard-coded error messages with `genErrors`
* Added `InjectError` to simplify error message types
=> `CERT` Conformance

.github/workflows/build.yml, README.md, default.nix, src/Ledger/Introduction.lagda, src/Makefile, src/latex/agda-latex-macros.sty
This adds the Conway spec to nix as the attribute `ledger.conway` and link it from the README. Also updates a bunch of deprecated CI actions.
=> Build the Conway spec in CI

src/Ledger/Address.lagda, src/Ledger/Foreign/HSLedger/BaseTypes.agda, src/Ledger/ScriptValidation.agda, src/Ledger/Transaction.lagda, src/Ledger/Utxow.lagda, src/ScriptVerification/HelloWorld.agda, src/ScriptVerification/Lib.agda, src/ScriptVerification/SucceedIfNumber.agda
This simplifies the marshalling to Haskell since we want a data type on the Haskell side and not an `Either`. Also it makes the spec easier to follow.
=> Make Credential a proper data type

src/Ledger/BaseTypes.lagda, src/Ledger/Certs.lagda, src/Ledger/Chain.lagda, src/Ledger/Crypto.lagda, src/Ledger/Epoch.lagda, src/Ledger/EssentialAgda.lagda, src/Ledger/GovernanceActions.lagda, src/Ledger/Introduction.lagda, src/Ledger/PParams.lagda, src/Ledger/Ratify.lagda, src/Ledger/TokenAlgebra.lagda
=> Capitalization of Sec heads to conform with previous eras

src/Axiom/Set.agda, src/Interface/IsSet.agda, src/Ledger/Address.lagda, src/Ledger/Ledger/Properties.agda, src/Ledger/Properties.agda, src/Ledger/Script.lagda, src/Ledger/Utxow.lagda, src/Ledger/Utxow/Properties.agda, src/latex/agda-latex-macros.sty
Closes #416 and #407. Because of issues with instance resolution, I had to add `HasInlineDatum` and `UsesV3Features` as explicit data types.
=> Add support for Plutus versions

src/Ledger/Certs.lagda
I've tested this locally and it works as expected, so it should be fine. We can revert this change once https://github.com/agda/agda/issues/7380 is fixed.
=> Work around MAlonzo bug

src/Ledger/Ratify.lagda
There was a mistake in the logic that allowed proposals that require CC votes to be passed in no-confidence state.
=> Prevent proposals from being accepted in no-confidence

src/Interface/ComputationalRelation.agda, src/Ledger/Ratify.lagda, src/Ledger/Ratify/Properties.agda
=> `RATIFY` conformance

scripts/bump-executable-spec.sh
This PR adds a script that builds the executable script Haskell library and copies all the files to the `cardano-ledger-executable-spec` repo. This will partially automate the bumping the executable spec for conformance testing.
=> Added a helper script for bumping the executable spec repo

.github/workflows/build.yml
Since we don't want to tag each new commit on branch `haskell-package` and only wish to tag a commit manually if that is used as an SRP in `cardano-ledger`, this PR removes the auto tagging from the GHA job. The instructions should be updated on the `cardano-ledger` side as a follow-up to this.
=> Stop auto tagging `haskell-package` commits

.github/workflows/build.yml, .github/workflows/pr_merged.yml
- Create an orphan branch (`MAlonzo-code`) for the generated code
- When opening a PR for a feature branch, create a separate branch
based on the `MAlonzo-code` branch which will contain newly
generated code from the feature branch
- Once the PR is successfully merged, the branch based on
`MAlonzo-code` gets squash merged into `MAlonzo-code` and deleted
Esentially, the above setup attempts to replicate
the git feature branch workflow for the generated code,
where the `MAlonzo-code` branch corresponds to the `main` / `master`
branch.
There will probably be some conflicts from time to time but these will be taken care of automatically by rebasing.
I opted to always keep the most recent changes, so the changes from the `*-MAlonzo` "feature" branches, rather than the ones from `MAlonzo-code`. …
=> Improve `MAlonzo` workflow

src/Axiom/Set/Properties.agda, src/Ledger/Gov.lagda, src/Ledger/Ledger/Properties.agda
=> DO NOT MERGE: Ratify governance actions in the correct order

src/Axiom/Set.agda, src/Interface/HasAdd/Instance.agda, src/Ledger/Address.lagda, src/Ledger/Certs/Haskell/Properties.agda, src/Ledger/Crypto.lagda, src/Ledger/Foreign/HSLedger/Core.agda, src/Ledger/Foreign/LedgerTypes.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/PParams.lagda, src/Ledger/Script.lagda, src/Ledger/Set/Theory.agda, src/Ledger/Transaction.lagda, src/Ledger/Types/Epoch.agda, src/ScriptVerification/LedgerImplementation.agda, src/ScriptVerification/Prelude.agda
=> Improve output of generrors

.github/workflows/build.yml
It seems like using `--depth 1` for fetching can sometimes mess things up, hence use `--unshallow` instead.
=> Fix `MAlonzo` code generation workflow

src/Ledger/Ratify.lagda
=> Fix `ccMinSize` check

.github/workflows/build.yml
As the title suggests. Broke up the workflow into multiple jobs as this is how parallelisation is achieved. This necessitated the upload of `docs/` as artifacts and merge downloading them, as different jobs have different runners with separate working directories.
=> Parallelise workflow

src/Ledger/Conway/Conformance/Foreign/HSLedger/Core.agda, src/Ledger/Conway/Conformance/Ledger.lagda, src/Ledger/Conway/Conformance/Utxo.agda, src/ScriptVerification/LedgerImplementation.agda
This PR modifies the alternative spec so that the deposit update happens in the LEDGER rule instead of the UTXO rule like in the implementation. It also makes the `isSigned` check always succeed in conformance testing.
=> Removed deposit updating from Haskell version of UTXO

CHANGELOG.md, src/Ledger/Conway/Conformance/Epoch.agda, src/Ledger/Conway/Conformance/Ratify.agda, src/Ledger/Conway/Foreign/HSLedger/Ratify.agda, src/Ledger/Epoch.lagda, src/Ledger/PDF/ConwayBootstrap.lagda, src/Ledger/Ratify.lagda
=> Change the way SPO votes are counted (Fix)

src/Ledger/Conway/Foreign/ExternalFunctions.agda, src/Ledger/Conway/Foreign/HSLedger/BaseTypes.agda, src/Ledger/Conway/Foreign/HSLedger/Core.agda, src/Ledger/Conway/Foreign/HSLedger/Gov.agda, src/Ledger/Conway/Foreign/HSLedger/NewEpoch.agda, src/Ledger/Conway/Foreign/HSLedger/Utxo.agda, src/Ledger/Conway/Foreign/Util.agda, src/Ledger/hs-src/Lib.hs, src/Ledger/hs-src/test/UtxowSpec.hs
This PR makes it possible to pass the `isSigned` function from Haskell to Agda via the `ExternalFunctions` record. 
closes https://github.com/IntersectMBO/formal-ledger-specifications/issues/593
=> Add a way to pull in functions from the Haskell implementation

scripts/bump-executable-spec.sh, src/Ledger/Certs.lagda, src/Ledger/Certs/Properties.agda, src/Ledger/Conway/Conformance/Certs.agda, src/Ledger/Conway/Conformance/Certs/Properties.agda, src/Ledger/Conway/Foreign/HSLedger/Core.agda, src/Ledger/hs-src/test/UtxowSpec.hs, src/ScriptVerification/HelloWorld.agda, src/ScriptVerification/LedgerImplementation.agda, src/ScriptVerification/Lib.agda, src/ScriptVerification/SucceedIfNumber.agda
This PR modifies some of the types in the Ledger models. I also fixed a bug in the spec that prevented delegations to `NoConfidence` and `AlwaysAbstain` delegatees.
related: 
https://github.com/IntersectMBO/cardano-ledger/issues/4254
https://github.com/IntersectMBO/cardano-ledger/pull/4741
=> Updated `ADHash`, fixed `DELEGS`

src/Ledger/Address.lagda, src/Ledger/hs-src/test/UtxowSpec.hs, src/ScriptVerification/HelloWorld.agda, src/ScriptVerification/Lib.agda, src/ScriptVerification/SucceedIfNumber.agda
=> `stake` field of `BaseAddr` should be optional

src/Ledger/Conway/Conformance/Utxow/Properties.agda
=> Replaced handwritten error messages with `genErrors` in the `UTXOW` rule

.github/workflows/build.yml
By checking the existence of the automatically created `*-MAlonzo` branch on each workflow run and creating the branch if the check fails, rather than only running the branch creation on PR open events, we are reducing the likelihood of missing the branch creation as happened in #607. The `*-MAlonzo` branch creation step was skipped there for some reason (probably an issue with one of the webhooks in the `if` check that should have triggered the step) which caused some problems down the line.
=> Check if `*-MAlonzo` branch exists on each run

src/Ledger/Address.lagda, src/latex/agda-latex-macros.sty
=> Document changes to BaseAddr

src/Ledger/Conway/Conformance/Gov.agda, src/Ledger/Conway/Conformance/Gov/Properties.agda, src/Ledger/Conway/Conformance/Ledger.agda, src/Ledger/Conway/Conformance/Utxo.agda, src/Ledger/Conway/Foreign/HSLedger/Utxo.agda
Removing some more code duplication between Ledger and Conformance to simplify the equivalence proof in #585.
=> Reuse ledger code in conformance

shell.nix, src/Ledger/Certs.lagda, src/Ledger/Certs/Properties.agda, src/Ledger/Conway/Conformance/Certs.agda, src/Ledger/Conway/Conformance/Certs/Properties.agda, src/Ledger/Conway/Foreign/HSLedger/Address.agda, src/Ledger/Conway/Foreign/HSLedger/BaseTypes.agda, src/Ledger/Conway/Foreign/HSLedger/Core.agda, src/Ledger/Conway/Foreign/HSLedger/ExternalStructures.agda, src/Ledger/Conway/Foreign/HSLedger/Utxo.agda, src/Ledger/Ledger/Properties.agda, src/Ledger/PParams.lagda, src/Ledger/ScriptValidation.agda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda, src/Ledger/Utxow.lagda, src/Ledger/hs-src/Lib.hs, src/Ledger/hs-src/test/UtxowSpec.hs, src/ScriptVerification/LedgerImplementation.agda
Adds `reg` cert, which behaves similarly to `delegate c nothing nothing d`, except that it doesn't require witnessing. This is the legacy staking address registration certificate that we still want to support in Conway and hopefully we can get rid of in the future.
Adds `HSVKey`, which stores the verification key together with the hash that's provided during translation in conformance testing. This fixes the issue where the value of the VKey itself is used as the hash, which caused conformance tests to fail.
related: https://github.com/IntersectMBO/cardano-ledger/pull/4780
closes https://github.com/IntersectMBO/formal-ledger-specifications/issues/615
=> Added `reg` cert, fixed hashing of `VKey`s

src/Ledger/Conway/Foreign/HSLedger/Core.agda
This is necessary to be able to run Imp conformance tests which use a different value for `SlotsPerEpoch`.
The proper approach would be to implement https://github.com/IntersectMBO/formal-ledger-specifications/issues/624, but this will unblock me for the time being.
=> Tweaked SlotsPerEpoch

CHANGELOG.md, src/Ledger/Certs.lagda, src/Ledger/Conway/Foreign/HSLedger/Core.agda, src/Ledger/Conway/Foreign/HSLedger/Utxo.agda, src/Ledger/Utxow.lagda
This PR adds the credentials used for collaterals to the set of required witnesses.
The `reg` cert must now be witnessed when the deposit is non-zero. This makes the old registration certificate behave the same way as it does in the Haskell implementation.
=> Added witnessing for collaterals

src/Ledger/Conway/Conformance/Script.agda, src/Ledger/Conway/Conformance/Utxow.agda, src/Ledger/Conway/Foreign/HSLedger/Core.agda, src/Ledger/Conway/Foreign/HSLedger/ExternalStructures.agda, src/Ledger/Conway/Foreign/HSLedger/Transaction.agda, src/Ledger/Conway/Foreign/HSLedger/Utxo.agda, src/Ledger/Transaction.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxow.lagda, src/Ledger/hs-src/Lib.hs
This PR adds the `HSPlutusScript`, which has the hash of the script and the size of the serialization of that script.
I also had to make a change to how `refScriptsSize` is calculated, because the implementation does not remove duplicate scripts and adds together the sizes of all the scripts even when there are multiple with the same hash.
=> Added `HSPlutusScript`, changed `refScriptsSize`

src/Ledger/Conway/Conformance/Utxow.agda, src/Ledger/Script.lagda, src/Ledger/Utxow.lagda
=> Witnesses for native scripts in reference inputs

CHANGELOG.md, src/Ledger/Certs.lagda, src/Ledger/Conway/Conformance/Certs.agda, src/Ledger/Conway/Conformance/Certs/Properties.agda, src/Ledger/Conway/Conformance/Equivalence.agda, src/Ledger/Conway/Conformance/Equivalence/Certs.agda, src/Ledger/Conway/Conformance/Equivalence/Deposits.agda, src/Ledger/Utxo.lagda
This PR changes the `DELEG-dereg` rule so that the deposit can be zero. In the implementation the deposit is optional and if it's not provided, we translate that to a deposit of zero. The implementation does that for backwards compatibility because the previous eras did not have a deposit field in the `dereg` cert.
closes #636
=> Allow legacy `dereg` certs

src/Ledger/Conway/Conformance/Equivalence.agda, src/Ledger/Conway/Conformance/Equivalence/Base.agda, src/Ledger/Conway/Conformance/Equivalence/Bisimilarity.agda, src/Ledger/Conway/Conformance/Equivalence/Certs.agda, src/Ledger/Conway/Conformance/Equivalence/Convert.agda, src/Ledger/Conway/Conformance/Equivalence/Deposits.agda, src/Ledger/Conway/Conformance/Equivalence/Gov.agda, src/Ledger/Conway/Conformance/Equivalence/Map.agda, src/Ledger/Conway/Conformance/Equivalence/Utxo.agda
I noticed that the equivalence proof was not marked as `--safe` and in fact one of the modules had a `--allow-unsolved-metas` still left in it. This PR fixes that.
=> Mark `Ledger.Conway.Conformance.Equivalence` safe

src/Ledger/Enact.lagda, src/Ledger/Transaction.lagda
This fixes the indentation of records in Figures 17 and 44 in the PDF.
=> Fix indentation of record fields in PDF

src/Ledger/GovernanceActions.lagda
=> Disallow empty withdrawal proposals

src/Ledger/Conway/Conformance/Utxo.agda, src/Ledger/Transaction.lagda, src/Ledger/Utxo.lagda, src/Ledger/Utxo/Properties.lagda
Addresses #342.
Original:
Other:
Left:
=> Eliminate Boolean properties

src/Ledger/Conway/Foreign/HSLedger/ExternalStructures.agda
There was no need to be unsafe here. Our code just happened to not match on that proof, but this could have broken at any time when doing refactoring. In the Consensus spec (which copies our code), this actually caused a crash.
=> Replace a call to `error` in our FFI with a safe alternative

src/Ledger/Conway/Conformance/Gov/Properties.agda, src/Ledger/Gov/Properties.agda, src/Ledger/GovernanceActions.lagda
The previous PR forgot to add some parentheses so the condition was actually incorrect.
=> Empty withdrawals condition fix

src/Ledger/Certs.lagda, src/Ledger/Chain.lagda, src/Ledger/Crypto.lagda, src/Ledger/Enact.lagda, src/Ledger/Epoch.lagda, src/Ledger/Gov.lagda, src/Ledger/GovernanceActions.lagda, src/Ledger/Introduction.lagda, src/Ledger/Ledger.lagda, src/Ledger/NewPP.lagda, src/Ledger/PPUp.lagda, src/Ledger/PParams.lagda, src/Ledger/Ratify.lagda, src/Ledger/TokenAlgebra.lagda, src/Ledger/Transaction.lagda, src/Ledger/Utxo.lagda, src/MidnightExample/Ledger.lagda
This closes issue #656
+ Remove all `\begin{code}[hide]` blocks surrounding occurrences of `field` keyword
+ Unhide record constructor bracket syntax definitions, since this was inconsistent (some constructor syntax definitions were hidden and some were not).
+ Make indentation convention for field names in `lagda` files consistent.
=> Make the usage of field keyword consistent

src/Ledger/Conway/Conformance/Equivalence.agda, src/Ledger/Conway/Conformance/Equivalence/Gov.agda, src/Ledger/Conway/Conformance/Gov.agda, src/Ledger/Conway/Conformance/Gov/Properties.agda, src/Ledger/Conway/Conformance/Ledger.agda, src/Ledger/Conway/Conformance/Ledger/Properties.agda, src/Ledger/Gov.lagda, src/Ledger/Gov/Properties.agda, src/Ledger/GovernanceActions.lagda, src/Ledger/Ledger.lagda, src/Ledger/Ledger/Properties.agda, src/latex/agda-latex-macros.sty
This PR moves the action-specific predicates in `GOV-Propose` to `actionWellFormed` and adds a check that makes sure all the receiving staking credentials of a `TreasuryWithdrawal` are registered when the proposal is made.
This probably requires some changes to the prose. It seemed like the prose about `actionWellFormed` was already outdated before these changes, because it only mentioned we check the parameter updates, but we also had some conditions about treasury withdrawals as well.
I also added two other predicate checks to the GOV rule which are present in the implementation:
- In `GOV-Propose`: the return address of a new proposal must be a registered staking credential
- In `GOV-Vote`: the proposal being voted for must not be expired
=> Moved action specific predicates to actionWellFormed and fix a conformance failure

src/Ledger/Fees.lagda, src/Ledger/PDF.lagda, src/Ledger/Utxo.lagda, src/latex/agda-latex-macros.sty, src/latex/conway-ledger.tex
This PR addresses #408.
It also:
- Formats the tex code in `Ledger.Fees`
- Includes `Ledger.Fees` in the PDF (both Conway and Cardano)
- Fixes a typo
=> 408 document changes to fee calculation wr ref scripts

nix/sources.json
Just a version bump. For some reason GHC didn't build on my system anymore with that old version. Not sure how that could have happened, but this fixes it.
=> Bump the nix channel from 21.05 to 24.05

default.nix, src/checkTypeChecked.sh
Just a minor wording improvement so that it becomes clear what to do when the script that checks if files have been checked fails.
=> Improve the error message when a file hasn't been type checked

src/Ledger/Utxo.lagda
Fixes alignment issue in Figure 16/Conway | 14/Ledger
=> Fixes alignment of submodule contents in Utxo figure

Shakefile.hs, conformance-example/test/UtxowSpec.hs, hs-src/cardano-ledger-executable-spec.cabal, hs-src/src/MAlonzo/Code/Ledger/Foreign/API.hs
This is a revival of #270.
Closes #595.
Note that this does not pass conformance testing due to #745
=> Rename Lib to MAlonzo.Code.Ledger.Foreign.API

default.nix, shell.nix
This pull request fixes an issue where `nix-shell` fails to start a shell on macOS / darwin due to an invalid value when defining `export LOCALE_ARCHIVE`.
=> Fix nix `LOCALE_ARCHIVE` on darwin

latex/cardano-ledger.tex, src/Ledger.agda, src/Ledger/Rewards.lagda, src/Prelude.agda
This pull request adds a section on the calculation of Rewards.
We begin with
* a subsection that briefly motivates the reward system, and
* the definition of the function `maxPool`.
Troubles:
* Unfortunately, I will not be able to add the definition of `createRUpd` in this section, as `EpochState` is not available until later. — This is one instance where more advanced literate programming tools would be beneficial, which allow us to decouple the order of presentation for printing from the order of presentation for compilation.
Comments:
* I managed to hide the proof obligations that we do not divide by `0` from the PDF. However, as type class inference does not work very well with expressions, I had to introduce the seemingly superfluous quantity `1+a0`.
* In order to satisfy the proof …
=> Add section "Rewards"

default.nix
This pull request fixes an issue where the font "DejaVu Sans Mono" introduced in #743 is not present in the nix environment, and `fls-shake` fails to produce `cardano-ledger.pdf` on my machine.
=> Add `dejavu` fonts to TeX environment in `default.nix`

CHANGELOG.md, src/Ledger/Conway/Foreign/HSLedger/Core.agda, src/Ledger/Epoch.lagda, src/Ledger/Rewards.lagda, src/Ledger/Types/Epoch.agda, src/ScriptVerification/LedgerImplementation.agda
This pull request adds the function `createRUpd` to the specification.
Comments:
* I have decided to stay very close to the notation from the original Shelley specification in order to make it straightforward to check that the two specifications agree.
* 6 lines in the `where` clause of `createRUpd` are devoted to extracting fields from records. This is somewhat lengthy, but I am under the impression that `where` clauses in Agda do not support pattern matching. It would be beneficial to join at least 3 lines into a single line `open Snapshot pstakego;`, but I am not quite sure what the policy on record modules is — `open` is used a couple of times in the specification, but it is never explained in Section 1 or 2 of the PDF.
* I have added `poolParameters` to the `SnapShot` type and the …
=> Add `createRUpd` (PR)

src/Ledger/Epoch.lagda, src/Ledger/Epoch/Properties.agda, src/Ledger/Rewards.lagda
This pull request moves the rule `SNAP` and associated types such as `Snapshot` and `Snapshots`, out of the section "Epoch Boundary" into the section "Rewards". In addition, we add a copy of the illustrated description of the Reward Cycle from the Shelley specification.
The goal of this and subsequent pull requests is to make the "Epoch Boundary" section lighter and to group the topics that are specific to rewards into the "Rewards" section.
Comments:
* I have moved the definition of `stakeDistr` as-is, I have not included a solution of #679 in the scope of this particular pull request.
Context: #706, #679
=> Move `SNAP` to section "Rewards"

lib-exts/stdlib/Data/Rational/Properties.agda, src/Ledger/Conway/Epoch.lagda, src/Ledger/Conway/Foreign/HSLedger/ExternalStructures.agda, src/Ledger/Conway/PParams.lagda, src/Ledger/Conway/Rewards.lagda, src/Ledger/Conway/Types/Epoch.agda, src/Ledger/Conway/Types/Numeric/UnitInterval.agda
This pull requests adds invariants to the type `RewardUpdate` and adds the proofs for these invariants to `createRUpd`.
* I managed to confine the use of proof-irrelevance to the module `Ledger.Conway.Types.Numeric.UnitInterval` by using decidability via the function `fromUnitInterval-inUnitInterval`. In this way, we can avoid any discussion of this topic in the human-readable definition of `RewardUpdate`.
* The module `Data.Rational.Properties` uses special type classes such as `NonNegative` for the predicate `0 ≤`. I wasn't quite sure how to use these classes effectively — their main purpose seems to hide/automate the proof obligation that `NonZero y` in the division `x ÷ y`, but these classes have enough lemmas associated with them that they can compete with the properties of `≤`. I'm …
=> Add invariants to `RewardUpdate`

flake.nix
Adds a `required` Hydra job for each system that is an aggregate of all the others.
Also adds a top-level `required` job that is an aggregate of all systems' `required` jobs.
This enables us to configure only the top-level `required` job as a needed check in GitHub as `ci/hydra-build:required`, so that we have status check for everything.
Unrelated but also adds Hydra jobs for the development shells so that they are pushed to the cache.
This adds the following new flake outputs:
- `hydraJobs.required`
- `hydraJobs.{x86_64-linux,…}.required`
- `hydraJobs.{x86_64-linux,…}.devShells.…`
- ~~Any semantic changes to the specifications are documented in `CHANGELOG.md`~~
- ~~Code is formatted according to [CONTRIBUTING.md](https://github.com/input-output-hk/formal-ledger-specifications/blob/master …
=> add aggregate hydra jobs

build-tools/agda/nix/fls-agda.nix, default.nix
Resolves #827 
As spotted in the issue discussion, this is related to the circular dependency due to the naming differences for outputs on Macos.
This is the attempt of fixing this.
I would need CI to make sure that this is still working on Linux though 🙏🏼
=> Fix build on Mac

.github/workflows/ci.yml
Closes #859,renames `upload-artifacts` to `push-artifacts-to-branch` and minimizes CI permissions.
For security reasons `GITHUB_TOKEN` has read-only permissions for pull requests originating on forks of the repository ([source](https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token/)). This seems like a reasonable thing since it disallows forks from making arbitrary changes.
This PR resolves #859 by adding a check to run `upload-artifacts` only on branches originating from within the repository. This means that *-artifacts  branches will not be created for these PR's branches and thus the CI status will not depend on this step.
=> Disable upload-artifacts on external branches

build-tools/agda/src/Main.hs
Addresses the bug described in #851.
Closes #861.
=> Fix VV issue with line breaks inbetween unicode brackets

src/Ledger/Conway/Specification/Gov/Actions.lagda
The LaTeX `longtable` (and even the simple `table`) environment causes pandoc to put the markdown version of the table inside a `<div>` `</div>` block and this apparently prevents mkdocs from rendering the table correctly, despite the fact that we are using the markdown extension `md_in_html`.  Until a better solution is found, a workaround is to simply omit the table environment altogether, just use a tabular environment, and move the caption ("Types of Governance Actions") to a subsection title called "Table: Types of Governance Actions".
Also, for some reason, pandoc silently deletes the footnote in the table.
To resolve both the table rendering issue and the lost footnote, I suggest we hand-tweak the `Actions.lagda.md` file and commit it to the repo soon.  For now, however, the …
=> Fix the broken table in the `Gov.Actions` module

CHANGELOG.md, CONTRIBUTING.md, build-tools/static/latex/macros.sty, src/Ledger/Conway/Specification/Epoch.lagda, src/Ledger/Conway/Specification/Epoch/Properties.agda, src/Ledger/Conway/Specification/Epoch/Properties/GovDepsMatch.lagda.md, src/Ledger/Conway/Specification/PParams.lagda, src/Ledger/Conway/Specification/PoolReap.lagda.md
This is a rebasing of #719. And it is also a follow up to #832 after rebasing master.
Implements POOLREAP as a new independent STS, rather than trying to reuse existing constructs.
=> Implement POOLREAP on epoch transitions
