default.nix
nix/sources.json
nix/sources.nix

This should make CI a lot faster

Update the nixpkgs used for Agda & move them into nix/sources.nix

---

.github/workflows/build.yml
default.nix

alongside the PDFs . 
The landing page will look like this: https://bienpulenta.github.io/formal-ledger-specifications

Deploy html docs to github pages

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/GovernanceActions.lagda
src/Ledger/Ledger.lagda
src/Ledger/Tally.lagda
src/Ledger/Transaction.lagda
src/Ledger/Utxow.lagda

Split `txgov` into two fields

---

src/Axiom/Set/Map.agda
src/Ledger/Chain.lagda
src/Ledger/Deleg.lagda
src/Ledger/Epoch.agda
src/Ledger/GovernanceActions.lagda
src/Ledger/Ratify.lagda

Rework the CC with new features

---

CONTRIBUTING.md

add maintainer

---

src/Ledger/Deleg.lagda
src/Ledger/Utxo.lagda

This is in the CIP but was missing here.

Add Anchor to DRep registration cert

---

src/Axiom/Set.agda
src/Axiom/Set/Map/Dec.agda
src/Ledger/Chain.lagda
src/Ledger/Deleg.lagda
src/Ledger/GovernanceActions.lagda
src/Ledger/Prelude.agda
src/Ledger/Ratify.lagda
src/Ledger/Tally.lagda
src/Ledger/Utxo.lagda
src/Ledger/Utxo/Properties.lagda

This PR ensures that the deposits of governance actions are paid for in the transaction and also returns the deposit to the reward account once the governance action has been accepted or rejected.
resolves #68

Accounting for proposal deposits

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/GovernanceActions.lagda
src/Ledger/PParams.lagda
src/Ledger/Tally.lagda

Add well-formedness for protocol parameter updates

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/PParams.lagda
src/Ledger/Ratify.lagda

Add minimum AVS

---

src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/agda-ledger-executable-spec.cabal

Add `ToExpr` instances

---

.github/workflows/build.yml

Improve commit to gh-pages

---

src/Ledger/Introduction.lagda
src/Ledger/PDF.lagda
src/Ledger/PParams.lagda

Add prose explaining the new parameters added in the Conway era.
This PR addresses one of the items of issue #145.

Conway spec prose: Protocol parameters

---

src/Ledger/GovernanceActions.lagda
src/Ledger/PDF.lagda

This addresses three tasks in issue #145.  (GovernanceActions, Voting, and Enactment)

Conway spec prose: GovernanceActions, Voting, Enactment

---

src/Tactic/DeriveComp.agda

`reduceDec` is very slow. It's possible it can be optimised, but it wasn't used in a critical way in `deriveComputational` so it was easier to just replace it for now.
Also, getting rid of the nested macro call to `by-derive⇔` saves a few seconds of quoting and unquoting the STS constructors.
All in all this brings down the type checking time of `Ledger.Utxo` from 44s to 13s.

Don't use reduceDec in deriveComputational

---

src/Ledger/GovernanceActions.lagda

Treasury withdrawals should go to reward addresses

---

src/Ledger/Gov.lagda
src/Ledger/GovernanceActions.lagda

This is for consistency with certificates & easier validation for consumed & produced. Closes #157.

Add `deposit` field to proposals, and check its correctness

---

src/Ledger/Utxo.lagda

Computational instance for the UTXO rule

Computational UTxO rule

---

src/Axiom/Set/Map.agda
src/Everything.agda
src/Ledger/Chain.lagda
src/Ledger/Deleg.lagda
src/Ledger/GovernanceActions.lagda
src/Ledger/Ratify.lagda

- Move donations into treasury (closes #161)
- Turn CC hot and cold keys into `Credential`s
- Only refresh registered DReps when voting (closes #174)

Fix several smaller issues

---

src/Ledger/Ratify.lagda

Made CC vote No when below minCCSize

---

src/Axiom/Set.agda
src/Interface/Decidable/Instance.agda
src/Ledger/Crypto.lagda
src/Ledger/GovernanceActions.lagda
src/Ledger/PPUp.lagda
src/Ledger/PPUp/Properties.agda
src/Ledger/Script.lagda
src/Ledger/Utxo.lagda
src/Ledger/Utxow.lagda
src/Ledger/Utxow/Properties.agda

Computational proof for ENACT, and cleaned up proofs for PPUP and UTXOW.

More computational instances

---

src/Ledger/Chain.lagda
src/Ledger/Chain/Properties.agda
src/Ledger/GovernanceActions.lagda

Finish `NEWEPOCH`

---

src/Ledger/Ratify.lagda

Add `actualSPOVotes`

---

src/Ledger/Gov.lagda

There were conflicts between #223 and 8613454.
Also fixed a bug in the new precondition added to rule.

Fix broken build from changed GOV' rule

---

src/Ledger/PParams.lagda
src/latex/agda-latex-macros.sty

- leftover names after commit #b862cfd

PDF: s/ccTermLimit/ccMaxTermLength

---

default.nix
flake.nix

declare hydra jobs

---

src/Ledger/Deleg.lagda

Remove comments from code in Figure 16 as requested in one of the items in issue #146 todo list.

PDF cleanup: Figure 16 remove comments

---

src/Ledger/GovernanceActions.lagda
src/latex/agda-latex-macros.sty

Address the following items of issue #146

PDF cleanup: Figure 8

---

src/Ledger/Ratify.lagda

Partial addresses one item, fully addresses another item, of #282
The second is easy because we can avoid geq for natural numbers by hiding it in the `Ledger.Prelude` import.
The first task is harder because we use the natural zero and the rational zero in the same line.  It's easy to change from `ℚ.0ℚ` to `0ℚ`, however, so that's what I did.

Rename `ℚ.0ℚ` → `0ℚ` and `_ℚ.≥_` → `_≥_`

---

src/Axiom/Set/Map.agda
src/Ledger/Chain.lagda
src/Ledger/Deleg.lagda
src/Ledger/Deleg/Properties.agda
src/Ledger/Foreign/HSLedger.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/ScriptValidation.agda
src/Ledger/Utxo.lagda

- Add `dereg` cert
- `delegate` cert was wrong in many ways
- `DState` rewards had wrong type

Fix various issues with certificates

---

src/Ledger/Address.lagda
src/Ledger/Epoch.lagda
src/Ledger/Notation.lagda
src/Ledger/PDF.lagda
src/Ledger/Utxo.lagda

Lots of notations still need to be explained (or removed), but this is a start.

Add notation section & remove footnote remarks in favor of it

---

PDF-style-guide.md
src/Ledger/Chain.lagda
src/Ledger/Crypto.lagda
src/Ledger/Epoch.lagda
src/Ledger/Gov.lagda
src/Ledger/GovernanceActions.lagda
src/Ledger/Introduction.lagda
src/Ledger/Ledger.lagda
src/Ledger/PDF.lagda
src/Ledger/PParams.lagda
src/Ledger/Ratify.lagda
src/Ledger/Transaction.lagda
src/Ledger/Utxo.lagda
src/Ledger/Utxow.lagda
src/Makefile
src/latex/preamble.tex
src/latex/references.bib

- Replace `$` with parentheses
- Add bibliography (Closes #303)
- Aligning & reformatting figures

Various PDF fixes

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/Gov.lagda
src/Ledger/Gov/Properties.agda
src/Ledger/GovernanceActions.lagda
src/Ledger/Ledger.lagda
src/Ledger/Ledger/Properties.agda
src/Ledger/Utxo.lagda
src/Ledger/Utxow.lagda
src/Ledger/Utxow/Properties.agda

This ensures proper determinism for the proposal policy. Also, clean up GOV' rules a bit. Closes #343

Add `policy` field to `GovProposal`

---

src/Ledger/Abstract.agda
src/Ledger/Deleg.lagda
src/Ledger/Gov.lagda
src/Ledger/Gov/Properties.agda
src/Ledger/GovernanceActions.lagda
src/Ledger/ScriptValidation.agda
src/Ledger/Utxow.lagda

Add `Voter` type and use it for `ScriptPurpose`

---

src/Ledger/Deleg.lagda
src/Ledger/Deleg/Properties.agda
src/Ledger/Ratify.lagda
src/Ledger/Utxo.lagda

Simplify & cleanup some figures

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/Introduction.lagda
src/Ledger/Notation.lagda
src/Ledger/PParams.lagda
src/latex/agda-latex-macros.sty

Address some comments from the audit

---

src/Ledger/PDF.lagda
src/Ledger/PDF/ConwayBootstrapEnact.lagda
src/latex/conway-ledger.tex

Add appendix for bootstrapping `EnactState`

---

.github/workflows/build.yml

Push the cabal package to a branch in CI

---

.gitignore

Restructure .gitignore & steal some of it from the implementation

---

src/Ledger/GovernanceActions.lagda
src/Ledger/Introduction.lagda
src/Ledger/PDF.lagda
src/Ledger/Utxo.lagda
src/latex/agda-latex-macros.sty
src/latex/conway-ledger.tex

Fixes from the second part of the audit

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/PParams.lagda

This PR makes it possible to create valid protocol parameter updates. Currently it is only possible to modify the `a` parameter.

Enable basic PPUpdates

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/PParams.lagda

This reverts commit ccca65058c9ed8934417998dfdb1a7246a37a83b.

Revert "Made it possible to update PParams (#394)"

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/Gov.lagda
src/Ledger/Gov/Properties.agda
src/Ledger/GovernanceActions.lagda
src/Ledger/PParams.lagda
src/Ledger/Ratify.lagda

Add some missing explanations and some minor improvements

---

src/ScriptVerification/LedgerImplementation.agda

Fix merge issue

---

src/Ledger/Gov.lagda
src/Ledger/Gov/Properties.agda

While talking about an issue with conformance testing, I wasn't sure whether the enactability predicate was correct, so I proved this.

Add enactability property for singletons

---

src/Axiom/Set/Map/Dec.agda
src/Ledger/PDF.lagda
src/Ledger/Properties.agda

This PR adds a module containing a bunch of top-level properties that we should prove. Since CI won't pass if we have holes, the actual properties are commented out (and modules that become empty because of this as well, to avoid warnings).

Add a collection of (unproven) properties

---

src/Everything.agda
src/Ledger/Ledger.lagda
src/Ledger/PDF.lagda

Remove PPUP imports from Conway

---

src/Ledger/Deleg.lagda
src/Ledger/Enact.lagda
src/Ledger/Epoch.lagda
src/Ledger/Foreign/HSLedger.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/Gov.lagda
src/Ledger/Notation.lagda
src/Ledger/PParams.lagda
src/Ledger/Utxo.lagda
src/Ledger/hs-src/test/UtxowSpec.hs
src/ScriptVerification/Lib.agda
src/latex/agda-latex-macros.sty

There were smaller changes that I made while responding to the audit.

Various fixes for issues found by the audit

---

src/Ledger/PDF.lagda
src/Ledger/PDF/ConwayBootstrap.lagda
src/latex/conway-ledger.tex

Adds an Appendix describing the bootstrapping phase. Closes #94.

Conway bootstrap

---

src/Ledger/Foreign/HSLedger.agda
src/Ledger/Foreign/LedgerTypes.agda

Added Haskell types for thresholds

---

src/Ledger/Notation.lagda
src/latex/agda-latex-macros.sty

Add some explanations to the Notation section

---

src/Ledger/Utxo.lagda
src/Ledger/Utxow.lagda
src/latex/agda-latex-macros.sty

Add prose to UTxO section

---

default.nix
nix/sources.json
src/checkTypeChecked.sh

This time for real, hopefully. I've disabled profiling in the CI build, which is useless anyway and avoids the bug.

Update to Agda 2.6.4.3

---

src/Ledger/Foreign/HSLedger/BaseTypes.agda
src/Ledger/Foreign/HSLedger/Core.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/PParams.lagda
src/Ledger/hs-src/test/UtxowSpec.hs

Add `PParamsUpdate`

---

src/Ledger/Epoch.lagda
src/Ledger/Gov.lagda
src/Ledger/GovernanceActions.lagda
src/Ledger/Ratify.lagda
src/Ledger/Transaction.lagda
src/Ledger/Types/GovStructure.agda
src/ScriptVerification/LedgerImplementation.agda

Cleanup `Epoch` a bit, and a few other random things

---

src/Ledger/Notation.lagda
src/latex/iohk.sty

larger rightharpoonup; add note about the symbol to notation sec

---

src/agda2vec.py

This closes #472 by addressing the two problems revealed by the new code:
The example shown in the issue should now be typeset as in the screenshot below.

bugfix: formatting for mkStakeDistrs and others in Epoch

---

default.nix
src/Interface/HasOrder/Instance.agda

Fix FOD sha for agda-stdlib-classes

---

shell.nix
src/Axiom/Set/Map.agda
src/Ledger/Address.lagda
src/Ledger/Certs.lagda
src/Ledger/Chain.lagda
src/Ledger/Chain/Properties.agda
src/Ledger/Epoch.lagda
src/Ledger/Epoch/Properties.agda
src/Ledger/Foreign/HSLedger/Epoch.agda
src/Ledger/Foreign/HSLedger/NewEpoch.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/Ledger/Properties.agda
src/Ledger/Ratify.lagda
src/Ledger/Ratify/Properties.agda
src/Ledger/Set/Theory.agda
src/Ledger/Utxo.lagda

This covers the following:
- `SNAP`
- computing the by-credential distribution
- computing the by-vdeleg distribution
Closes #456.

Add stake distribution calculations

---

src/agda2vec.py

This address issue #482 
Vector elements with curly braces and union symbols were split (at the union symbol) into two vector elements.  This PR fixes that.

Bug in vertical vectors: ∪ˡ makes a new entry

---

src/Ledger/Certs.lagda
src/Ledger/Chain.lagda
src/Ledger/Enact.lagda
src/Ledger/Epoch.lagda
src/Ledger/Gov.lagda
src/Ledger/Ledger.lagda
src/Ledger/Ratify.lagda
src/Ledger/Utxo.lagda
src/Ledger/Utxow.lagda
src/agda2vec.py

This addresses most of the items in issue #478.  The remaining items may require longer-term efforts to fix, so we may want to merge this PR even if it doesn't fully close issue #478.

Fix figure readability issues

---

cardano-interface/CardanoInterface.agda
cardano-interface/cardano-interface.agda-lib

This is a basic interface that Ledger is supposed to provide for consensus.

Add `cardano-interface` library

---

src/Ledger/Certs.lagda
src/Ledger/Chain.lagda
src/Ledger/Enact.lagda
src/Ledger/Epoch.lagda
src/Ledger/Foreign/HSLedger/Gov.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/Gov.lagda
src/Ledger/Gov/Properties.agda
src/Ledger/GovernanceActions.lagda
src/Ledger/GovernanceActions/Properties.agda
src/Ledger/Ledger/Properties.agda
src/Ledger/Ratify.lagda
src/latex/agda-latex-macros.sty

Various small improvements to the PDF

---

src/Ledger/Introduction.lagda
src/Ledger/Ratify.lagda
src/latex/agda-latex-macros.sty

Fix font inconsistencies

---

CHANGELOG.md
src/Ledger/Certs.lagda
src/Ledger/Certs/Properties.agda
src/Ledger/Foreign/HSLedger/Certs.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/Ledger.lagda
src/Ledger/Ledger/Properties.agda
src/Ledger/ScriptValidation.agda
src/Ledger/Utxo.lagda
src/Ledger/Utxo/Properties.lagda

Closes #469. #493 should be merged before this.

Add deposit amount to `dereg`

---

src/Ledger/Epoch.lagda
src/Ledger/Epoch/Properties.agda
src/Ledger/Foreign/HSLedger/Core.agda
src/Ledger/Foreign/HSLedger/NewEpoch.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/Ledger/Properties.agda
src/Ledger/PParams.lagda

Add reward updates

---

src/Ledger/Chain.lagda
src/Ledger/Enact.lagda
src/Ledger/Utxo.lagda
src/Makefile
src/agda2vec.py

Improve readability of the figures (2)

---

src/Ledger/Gov.lagda
src/Ledger/Utxo.lagda

Readability of Figures: Fig 11 and Fig 16 adjustments.

---

src/Ledger/Certs.lagda
src/Ledger/Enact.lagda
src/Ledger/Epoch.lagda
src/Ledger/Gov.lagda
src/Ledger/GovernanceActions.lagda
src/Ledger/Introduction.lagda
src/Ledger/Notation.lagda
src/Ledger/PDF.lagda
src/Ledger/PDF/ConwayBootstrap.lagda
src/Ledger/PParams.lagda
src/Ledger/Ratify.lagda
src/Ledger/Transaction.lagda
src/Ledger/Utxo.lagda
src/Ledger/Utxow.lagda
src/agda2vec.py
src/latex/conway-ledger.tex
src/latex/references.bib

Conway spec proofread revisions

---

.github/workflows/build.yml
src/Ledger/hs-src/cardano-ledger-executable-spec.cabal

Improve `haskell package` GHA job

---

src/Ledger/Ratify.lagda

This fixes a conformance issue.

Use yes and no votes for total stake instead of non-abstaining ones

---

src/Ledger/Foreign/HSLedger/Ratify.agda
src/Ledger/hs-src/Lib.hs

Add debug info to RATIFY

---

src/Ledger/Ratify.lagda

Re-add MAlonzo bug workaround

---

src/Ledger/Ratify.lagda

Fix that `ccMinSize` was not respected with an empty committee

---

src/Ledger/Ratify.lagda

This PR fixes a bug that makes it impossible to pass `NoConfidence` and `UpdateCommittee` when the CC size is below `ccMinSize`.

Prevent invalid CC from blocking NoConfidence

---

src/Ledger/Certs.lagda
src/Ledger/Certs/Haskell.agda
src/Ledger/Certs/Haskell/Properties.agda
src/Ledger/Certs/Properties.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/ScriptValidation.agda
src/Ledger/Utxo.lagda
src/Ledger/Utxo/Properties.lagda

Closes #510. Waiting to merge this until conformance tests find this issue.

DO NOT MERGE: Add deposit amount to `deregdrep`

---

src/Ledger/Certs.lagda
src/Ledger/Enact.lagda
src/Ledger/Epoch.lagda
src/Ledger/Gov.lagda
src/Ledger/GovernanceActions.lagda
src/Ledger/Introduction.lagda
src/Ledger/Ledger.lagda
src/Ledger/Notation.lagda
src/Ledger/PDF.lagda
src/Ledger/PParams.lagda
src/Ledger/Ratify.lagda
src/Ledger/Transaction.lagda
src/Ledger/Utxo.lagda
src/Ledger/Utxow.lagda
src/latex/conway-ledger.tex
src/latex/references.bib

Many small random things I found. Removing a bunch of warnings.

Lots of minor cleanup changes

---

src/Ledger/Address.lagda
src/Ledger/Certs.lagda
src/Ledger/Certs/Haskell.agda
src/Ledger/Certs/Haskell/Properties.agda
src/Ledger/Certs/Properties.agda

DO NOT MERGE: Restrict withdrawals to KeyHashObj in subset relation

---

src/Ledger/Gov.lagda
src/Ledger/Gov/Properties.agda

Missing network id checks

---

src/Axiom/Set.agda
src/Interface/HasAdd/Instance.agda
src/Ledger/Address.lagda
src/Ledger/Certs/Haskell/Properties.agda
src/Ledger/Crypto.lagda
src/Ledger/Foreign/HSLedger/Core.agda
src/Ledger/Foreign/LedgerTypes.agda
src/Ledger/GovernanceActions.lagda
src/Ledger/PParams.lagda
src/Ledger/Script.lagda
src/Ledger/Set/Theory.agda
src/Ledger/Types/Epoch.agda
src/ScriptVerification/LedgerImplementation.agda
src/ScriptVerification/Prelude.agda

* experiment with manipulating a specific error string
* fix string add
* add Show instances for Credential and Set and ℙ
* add Show instances for more Ledger types
* fixed broken type class application
* incorporate suggestions from PR review and improve fail messages
* Fix order `KeyHashObj` and `ScriptHashObj` constructors in the FFI
---------

Improve output of generrors (#551)

---

src/Ledger/Gov.lagda
src/agda2vec.py
src/latex/agda-latex-macros.sty

hasParent needs to match GAs

---

.github/workflows/build.yml

Fix Conway PDF not being uploaded

---

src/Ledger/Epoch.lagda
src/Ledger/Ledger/Properties.agda

Remove unenactable governance actions in EPOCH

---

CHANGELOG.md
src/Ledger/Conway/Conformance/Gov.lagda
src/Ledger/Conway/Conformance/Gov/Properties.agda
src/Ledger/Gov.lagda
src/Ledger/Gov/Properties.agda

Prevent policy from being supplied with wrong actions

---

CHANGELOG.md
src/Ledger/Conway/Conformance/Epoch.lagda
src/Ledger/Conway/Conformance/Foreign/HSLedger/Ratify.agda
src/Ledger/Conway/Conformance/Ratify.lagda
src/Ledger/Epoch.lagda
src/Ledger/Ratify.lagda

Reverts IntersectMBO/formal-ledger-specifications#594

Revert "Change the way SPO votes are counted"

---

src/Ledger/hs-src/Lib.hs

Exported `ledgersStep`

---

src/Ledger/Conway/Conformance/Utxo.agda

This PR updates the deposit calculation function in the conformance version of the spec.

Fixed deposit change calculation in conformance

---

CONTRIBUTING.md

Add instructions to build without nix (#431)

---

src/Ledger/Address.lagda

Small typo on page 11

---

src/Ledger/Certs.lagda

A paragraph was duplicated by #659.

Fix duplication introduced by #659

---

.gitignore

Add latex/Conway to gitignore

---

.github/workflows/build.yml

It seems there's a problem with the CI at "Uploads (push)" stage.

Restructure repo (Fix)

---

scripts/prepare-conf-test.sh

Add script to prepare cardano-ledger for conformance test

---

.github/workflows/build.yml
.github/workflows/reusable.yml

Refactor workflows so that build products are reused, and build actions are isolated (easier to see warnings/errors)

Refactor workflows

---

.github/workflows/build.yml

Fix ci again

---

latex/preamble.tex
src/Ledger/Utxo.lagda

Move cleverref use; remove reference

---

src/Ledger/Conway/Foreign/HSLedger/BaseTypes.agda

This PR closes #745.
After this is merged, we need to open a PR in `cardano-ledger` to update the renaming of Lib to MAlonzo.Code.Ledger.Foreign.API.

Fix broken conformance testing

---

fls-shake/Main.hs

Closes #754 
We should however think of a better approach to the way we do hldiff.
Right now the logic is handled by the python script `hldiff.py` while the replacement words are stored in `latex/hldiff_list.txt`.
A good solution might be to do this replacement directly in `fls-shake`.

Fix pp scripts in fls-shake

---

.github/workflows/build.yml

Add step to upload artifacts to delete branch after merge

---

.github/workflows/build.yml

Fix deletion of `master-artifacts` branch, closing issue #772.

Fix deletion of master-artifacts

---

CHANGELOG.md
src/Ledger/Conway/Transaction.lagda
src/Ledger/Conway/Utxo.lagda
src/Ledger/Conway/Utxo/Properties.lagda
src/ScriptVerification/HelloWorld.agda
src/ScriptVerification/SucceedIfNumber.agda

move `txsize` from `TxBody` to `Tx`

---

CONTRIBUTING.md
build-tools/agda/nix/fls-agda.nix

Add `agda-mode` to `fls-agda.nix`

---

.github/workflows/ci.yml

Change condition on push-artifacts-to-branch step

---

.github/workflows/ci.yml
build-tools/static/hs-src/src/MAlonzo/Code/Ledger/Foreign/API.hs
src/Ledger/Conway/Conformance/Epoch.agda
src/Ledger/Conway/Conformance/Epoch/Properties.agda
src/Ledger/Conway/Conformance/Rewards.agda
src/Ledger/Conway/Foreign/HSLedger/Epoch.agda
src/Ledger/Conway/Foreign/HSLedger/NewEpoch.agda
src/Ledger/Conway/Foreign/HSLedger/Rewards.agda

This PR integrates recent changes to reward calculation in the Conformance framework (closes #873)
In addition it solves the broken build on `master` (closes #872)
And closes #856

Integrate reward calculation in Conformance

---

build-tools/static/md/mkdocs/includes/links.md
build-tools/static/md/mkdocs/includes/links.md.orig
src/Ledger/Conway/Specification/Enact.lagda.md
src/Ledger/Conway/Specification/Epoch.lagda.md
src/Ledger/Conway/Specification/Gov.lagda.md
src/Ledger/Conway/Specification/tmp

Migrate `Enact.lagda` and `Gov.lagda`  to `.lagda.md`

---

src/Ledger/Conway/Specification/Epoch.lagda.md

Add deposits to stake of SPOs for counting votes
